- name: make sure python3 and pip3 is installed
  package: 
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip

- name: install recent2 pip3 module
  shell: pip3 install recent2 --break-system-packages

- name: adjust /etc/bash.bashrc
  ansible.builtin.lineinfile:
    path: /etc/bash.bashrc
    line: export PROMPT_COMMAND='log-recent -r $? -c "$(HISTTIMEFORMAT= history 1)" -p $$'
